### ISSUE TITLE
Separate GitHub App sources

### ISSUE THREAD

**Issue by Quramy** [reg-viz/reg-suit#151]
### Motivation

For now, this repository provides the both reg-suit and it's plugins NPM packages and application code of GitHub App. But they have different deployment lifecycle and different dependencies. So CI jobs' durations time get longer because of the monorepo.

### Tasks

- [x] Create a repository for gh-apps
  - https://github.com/reg-viz/gh-app
- [x] Replace hard coding of `https://reg-viz.github.io/reg-suit/gh-app/` to the new URL
- [x] Delete the following package
  - reg-gh-app-*
- [x] Configure https://github.com/organizations/reg-viz/settings/apps/reg-suit
